name: Build

on: [ push, workflow_dispatch ]

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "OK"
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
  release:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        if: startsWith(github.ref, 'refs/tags/')
